# Generated by Django 5.0.1 on 2024-01-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AddField(
            model_name='author',
            name='author_id',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='book',
            name='book_id',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
