# Generated by Django 4.2.1 on 2023-09-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_signal_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signaltest',
            name='id',
        ),
        migrations.AlterField(
            model_name='signaltest',
            name='email',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
