# Generated by Django 4.2.1 on 2023-08-25 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resturant',
            fields=[
                ('rest_id', models.CharField(default='', max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.CharField(default='', max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('role_name', models.CharField(blank=True, max_length=50, null=True)),
                ('resturant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_rest', to='serializer_relation_app.resturant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_user', to='serializer_relation_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='resturant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_user', to='serializer_relation_app.user'),
        ),
    ]
