# Generated by Django 4.2.1 on 2023-08-25 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serializer_relation_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resturant',
            old_name='name',
            new_name='restname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
