# Generated by Django 5.0.1 on 2024-01-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='uri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
