# Generated by Django 5.0.1 on 2024-01-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_people_uri_alter_people_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
