# Generated by Django 4.1.7 on 2023-09-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('otp', models.IntegerField()),
                ('expires', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
