# Generated by Django 4.1.7 on 2023-09-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='phone',
        ),
        migrations.AddField(
            model_name='otp',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
