# Generated by Django 4.2.8 on 2023-12-27 15:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('user_id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('book_name', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='api.author')),
            ],
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('meta_id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_meta', to='api.author')),
            ],
        ),
        migrations.CreateModel(
            name='BookMeta',
            fields=[
                ('bookemeta_id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('launch_date', models.DateTimeField(default=datetime.datetime(2023, 12, 27, 20, 57, 54, 975295))),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_meta', to='api.book')),
            ],
        ),
    ]
