# Generated by Django 4.2.8 on 2023-12-27 15:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmeta',
            name='launch_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 27, 21, 9, 26, 975969)),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_meta', to='api.author'),
        ),
    ]
