# Generated by Django 4.2.8 on 2023-12-27 16:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_bookmeta_launch_date_alter_metadata_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmeta',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_meta', to='api.book'),
        ),
        migrations.AlterField(
            model_name='bookmeta',
            name='launch_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 27, 21, 33, 59, 547581)),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author_meta', to='api.author'),
        ),
    ]
